---
- name: AWS Webserver Route53 Domain
  hosts: localhost
  vars:
    region: "eu-west-1"

  tasks:
  - name: Get ELB DNS info
    amazon.aws.elb_application_lb_info:
      names: "webserverelb"
      region: "{{ region }}"
    register: elb

  - name: Create Route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ hostname }}.{{ domain }}"
      type: A
      overwrite: true
      value: "{{ elb.load_balancers[0].dns_name }}"
      alias: True
      alias_hosted_zone_id: "{{ elb.load_balancers[0].canonical_hosted_zone_id }}"