---
- name: Azure Webserver Resource Group
  hosts: localhost
  vars:
    resourcegroup: "webserver"
    location: "northeurope"

  tasks:
    - name: create Resource Group
      azure_rm_resourcegroup:
        name: "{{ resourcegroup }}"
        location: "{{ location }}"
