---
- name: Azure Webserver Infrastructure
  hosts: localhost
  vars:
    resourcegroup: "webserver"
    location: "northeurope"

  tasks:
    - name: Delete Resource Group and Content
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resourcegroup }}"
        location: "{{ location }}"
        force_delete_nonempty: true
        state: absent
