---
- name: Azure Webserver Infrastructure
  hosts: localhost
  vars:
    resourcegroup: "webserver"
    location: "northeurope"
    user: "azureuser"
    virtualnetwork_name: "webserver-net"
    project_name: "ansible"
    cidr: "10.0.0.0/16"
    webserver_subnet: "webserver_subnet"
    cidr_public_a: "10.0.1.0/24"
    availabilityset: "webserver_avail"
    webserver_nsg: "webserver_nsg"
    domain_sub: "web"

  tasks:
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resourcegroup }}"
        name: "{{ virtualnetwork_name }}"
        address_prefixes_cidr:
          - "{{ cidr }}"

    - name: Create a subnet
      azure_rm_subnet:
        resource_group: "{{ resourcegroup }}"
        virtual_network_name: "{{ virtualnetwork_name }}"
        name: "{{ webserver_subnet }}"
        address_prefix_cidr: "{{ cidr_public_a }}"

    - name: Create an availability set with advanced options
      azure_rm_availabilityset:
        name: "{{ availabilityset }}"
        location: "{{ location }}"
        resource_group: "{{ resourcegroup }}"
        platform_update_domain_count: 5
        platform_fault_domain_count: 3
        sku: Aligned

    - azure_rm_securitygroup:
        resource_group: "{{ resourcegroup }}"
        name: "{{ webserver_nsg }}"
        purge_rules: yes
        rules:
          - name: "AllowSSH"
            protocol: Tcp
            source_address_prefix:
              - "0.0.0.0/0"
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound
          - name: "AllowHTTP"
            protocol: Tcp
            source_address_prefix:
              - "0.0.0.0/0"
            destination_port_range:
              - 80
            access: Allow
            priority: 102

    - name: Create a public ip address for webserver1
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegroup }}"
        name: public_ip_webserver1
        allocation_method: static
        #domain_name: "webserver1{{ domain_sub }}"
      register: webserver1_pub_ip

    - name: Create a public ip address for webserver2
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegroup }}"
        name: public_ip_webserver2
        allocation_method: static
        #domain_name: "webserver2{{ domain_sub }}"
      register: webserver2_pub_ip

    - name: Create a network interface for webserver1
      azure_rm_networkinterface:
        name: "webserver1_nic01"
        resource_group: "{{ resourcegroup }}"
        virtual_network: "{{ virtualnetwork_name }}"
        subnet_name: "{{ webserver_subnet }}"
        security_group: "{{ webserver_nsg }}"
        ip_configurations:
          - name: "webserver1_nic01_ipconfig"
            public_ip_address_name: "public_ip_webserver1"
            primary: True

    - name: Create a network interface for webserver2
      azure_rm_networkinterface:
        name: "webserver2_nic01"
        resource_group: "{{ resourcegroup }}"
        virtual_network: "{{ virtualnetwork_name }}"
        subnet_name: "{{ webserver_subnet }}"
        security_group: "{{ webserver_nsg }}"
        ip_configurations:
          - name: "webserver2_nic01_ipconfig"
            public_ip_address_name: "public_ip_webserver2"
            primary: True

    - name: Create Webserver1 VM
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup }}"
        name: webserver1
        vm_size: Standard_A1_v2
        os_type: Linux
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ user }}/.ssh/authorized_keys"
            key_data: "{{ ssh_public_key }}"
        availability_set: "{{ availabilityset }}"
        managed_disk_type: Standard_LRS
        admin_username: "{{ user }}"
        network_interfaces: webserver1_nic01
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: "8.0"
          version: latest
        tags:
          Ansible: "webserver"

    - name: Create Webserver2 VM
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup }}"
        name: webserver2
        vm_size: Standard_A1_v2
        os_type: Linux
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ user }}/.ssh/authorized_keys"
            key_data: "{{ ssh_public_key }}"
        availability_set: "{{ availabilityset }}"
        managed_disk_type: Standard_LRS
        admin_username: "{{ user }}"
        network_interfaces: webserver2_nic01
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: "8.0"
          version: latest
        tags:
          Ansible: "webserver"
