---
- name: Azure Webserver Compute Website
  hosts: tag_Ansible_webserver
  become: true

  tasks:
    - name: Download Website from Github
      ansible.builtin.git:
        repo: "{{ gitrepo }}"
        dest: "/var/www/html"
