---
- name: Azure Webserver Compute Website
  hosts: tag_Ansible_webserver
  become: yes

  tasks:
  - name: Download Website from Github
    git:
      repo: "{{ gitrepo }}"
      dest: "/var/www/html"