---
- name: Setup Website
  hosts: tag_Ansible_webserver
  become: true

  vars:
    facts: Chuck Norris can kill two stones with one bird

  tasks:
    - name: Copy Chuck Norris image
      ansible.builtin.copy:
        src: chuck_norris.jpg
        dest: /var/www/html/chuck_norris.jpg
        owner: root
        group: root
        mode: "0644"

    - name: Copy Index Template
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"
