---
- hosts: localhost
  connection: local
  vars:
    vpc_name: "Tower-vpc"
    project_name: "ansibleawx"
    region: "eu-central-1"
    cidr: "10.1.0.0/16"
    cidr_public_a: "10.1.0.0/24"
    zone1: "a"

  tasks:
    - name: Remove towerserver
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: absent
        filters:
          tag:project: "{{ project_name }}"

    - name: Remove keypair
      amazon.aws.ec2_key:
        name: tower_keypair
        state: absent
        region: "{{ region }}"

    - name: Get VPC info
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc

    - name: Get Subnets info
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc.vpcs[0].id }}"
      register: subnets

    - name: Set Subnet cidr_block
      ansible.builtin.set_fact:
        subnet_cidr: "{{ subnets.subnets|map(attribute='cidr_block')|list }}"

    - name: vpc internet gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpcs[0].id }}"
        state: absent

    - name: Delete Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        state: absent
        vpc_id: "{{ vpc.vpcs[0].id }}"
        cidr: "{{ item }}"
      loop: "{{ subnet_cidr }}"

    - name: Remove VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ cidr }}"
        region: "{{ region }}"
        state: absent
