---
- name: Configure Cloud Credentials in AWX
  hosts: localhost
  connection: local

  vars:
    aws_path: ~/.aws/credentials

  tasks:
    - name: AWS Credential file exist
      ansible.builtin.stat:
        path: "{{ aws_path }}"
      register: aws_cred_stat

    - name: Read AWS Credential file
      ansible.builtin.set_fact:
        aws_cred: "{{ lookup('file', {{ aws_path }}) }}"
      when: aws_cred_stat.stat.exist

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred }}"
