---
- name: Configure Cloud Credentials in AWX
  hosts: localhost
  connection: local

  vars:
    aws_path: ~/.aws/credentials

  tasks:
    - name: AWS Credential file exist
      ansible.builtin.stat:
        path: "{{ aws_path }}"
      register: aws_cred_stat

    - name: Read AWS Credential file
      ansible.builtin.set_fact:
        aws_cred: "{{ lookup('file', aws_path).splitlines() }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred }}"

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred }}"

    - name: Convert to list
      ansible.builtin.set_fact:
        aws_cred_list: "{{ aws_cred|list }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred_list[2] }}"

    - name: Set AWS Access Key
      ansible.builtin.set_fact:
        aws_access_key_id: "{{ aws_cred_list[1]| split('=') }}"
      when: aws_cred_stat.stat.exists

    - name: Set AWS Secret Key
      ansible.builtin.set_fact:
        aws_secret_access_key: "{{ aws_cred_list[2]| split('=') }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_access_key_id }}"

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_secret_access_key }}"
