---
- name: Configure Cloud Credentials in AWX
  hosts: localhost
  connection: local

  vars:
    aws_path: ~/.aws/credentials

  tasks:
    - name: AWS Credential file exist
      ansible.builtin.stat:
        path: "{{ aws_path }}"
      register: aws_cred_stat

    - name: Read AWS Credential file
      ansible.builtin.set_fact:
        aws_cred: "{{ lookup('file', aws_path).splitlines() }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred }}"

    # - name: Fix
    #   ansible.builtin.set_fact:
    #     aws_cred_fix: '{{ aws_cred|regex_replace("/[,]/",'') }}'
    #   when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred }}"

    - name: Convert to JSON
      ansible.builtin.set_fact:
        aws_cred_list: "{{ aws_cred|list }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred_list[2] }}"

    - name: Convert to JSON
      ansible.builtin.set_fact:
        aws_cred_json: "{{ aws_cred_list|to_nice_json }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred_json }}"
