---
- name: Configure Cloud Credentials in AWX
  hosts: localhost
  connection: local

  vars:
    aws_path: ~/.azure/credentials

  tasks:
    - name: AWS Credential file exist
      ansible.builtin.stat:
        path: "{{ aws_path }}"
      register: aws_cred_stat

    - name: Read AWS Credential file
      ansible.builtin.set_fact:
        aws_cred: "{{ lookup('file', aws_path) }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred }}"

    - name: Convert to JSON
      ansible.builtin.set_fact:
        aws_cred_json: "{{ aws_cred|to_json(indent=4, sort_keys=True) }}"
      when: aws_cred_stat.stat.exists

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ aws_cred_json }}"
